location: San Francisco, CA
carrier: UNLOCKED/US
interval: 10000 # 10 seconds
stores:
  - R744 # Union Square
parts:
  - MFYT4HN/A # iPhone 17 Pro Max 256GB Orange
notifications:
  alwaysNotify: false
